version: '3.7'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=readspacev2
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - mynetwork

  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '8080:8080'
    depends_on:
      - db
      - redis
    environment:
      - REDIS_ADDR=redis:6379
    volumes:
      - ./backend/.env:/backend/.env
      - ./backend/migrations/:/backend/migrations/
      - ./backend:/backend
    networks:
      - mynetwork

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  postgres_data:

