version: '3.7'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=readspacev2
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  backend:
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - db
    volumes:
      - ./backend/.env:/backend/.env
      - ./backend/migrations/:/backend/migrations/
volumes:
  postgres_data:
