basePath: /api/v1
definitions:
  entity.Login:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  entity.UserInput:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample server celler server.
  title: Readspace API
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Authenticate using username and password to get a token
      parameters:
      - description: Credentials for login
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/entity.Login'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully authenticated, token returned
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Authenticate a user and obtain a token
      tags:
      - authentication
  /user:
    post:
      consumes:
      - application/json
      description: Create a new user with the input payload
      parameters:
      - description: User entity to add
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/entity.UserInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: string
      summary: Create a new user
      tags:
      - users
swagger: "2.0"
